import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  projectSidebar: [
    'protocol',
    'auth-protocol',
    'cloud-auth',
    'privacy-connectivity',
    'roadmap-450mt',
    'hardware-validation',
    'test-coverage',
    'audit-b1-b2',
    {
      type: 'category',
      label: 'Historical Plans',
      items: [{ type: 'autogenerated', dirName: 'superpowers/plans' }],
    },
  ],
};

export default sidebars;
